name: Swagger

on: 
  pull_request:
  workflow_dispatch:

jobs:
  swagger:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Refresh swagger doc
      shell: bash
      run: |
        go get -u github.com/swaggo/swag/cmd/swag
        swag init --md ./
      env:
        GOPATH: /home/runner/work/woodpecker/go

    - name: Update swagger resource
      uses: test-room-7/action-update-file@v1
      with:
        file-path: docs/*
        commit-msg: Update swagger
        github-token: ${{ secrets.REPO_TOKEN }}
