name: Swagger

on: 
  pull_request:
  workflow_dispatch:

jobs:
  swagger:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Refresh swagger doc
      shell: bash
      run: |
        wget https://github.com/swaggo/swag/releases/download/v1.16.3/swag_1.16.3_Linux_amd64.tar.gz
        tar xvzf swag_1.16.3_Linux_amd64.tar.gz
        ./swag init --md ./

    - name: Update swagger resource
      uses: test-room-7/action-update-file@v1
      with:
        file-path: docs/*
        commit-msg: Update swagger
        github-token: ${{ secrets.REPO_TOKEN }}
